### ISSUE TITLE
Missing characters for WiFi passphrase

### ISSUE THREAD

**Issue by seswho** [cmdc0de/corncon2023#1]
Hello, understand there is a limit of memory on the badges. I am unable to connect the badge to my home WiFi because the passphrase uses characters not found on the badge. Could create another SSID for them, not sure I want to do that just for the badges.

Could the firmware be upgraded to include all of the special characters found on a keyboard?

**Comment by cmdc0de** [comment]
Is there a specific character you're looking for?  @seswho I'll check this in tonight and push a new version such that if you connect to WIFI and then go to settings->update you'll get a new keyboard with the following characters added:
.,/-_

If I missed on: simply add it to the K1 string in the vkeyboard.h file.

**Comment by seswho** [comment]
Hi,

Sorry, just saw your question.

Thanks for adding the characters listed in your question.

I must be strange or something. My passphrase contains .[(}~+ in it.

--
Steve Steiner
steveATseswhoDOTcom

“Oh, so they have internet on computers now!”
Homer Simpson

------- Original Message -------

**Comment by cmdc0de** [comment]
Ah I’ll need to add those as I don’t think I added  []I’ll do that tonight and push a new release Sent and "spell corrected" by my iPhoneOn Oct 13, 2023, at 11:01, Steven Steiner ***@***.***> wrote:﻿
Hi,

Sorry, just saw your question.

Thanks for adding the characters listed in your question.

I must be strange or something. My passphrase contains .[(}~+ in it.

--
Steve Steiner
steveATseswhoDOTcom

“Oh, so they have internet on computers now!”
Homer Simpson

------- Original Message -------

**Comment by cmdc0de** [comment]
@seswho symbols added and posted to patch server.
